### ISSUE TITLE
Lint error "TrustAllX509TrustManager" from usercentrics SDK

### ISSUE THREAD

**Issue by HughIngram** [Usercentrics/android-sample#12]
artifact: `com.usercentrics.sdk:usercentrics-ui:2.9.1`
steps to recreate:
- project with usercentrics as a dependency
- run lint from the CLI, e.g. `./gradlew :lib:lintDeRelease -PdisablePreDex --max-workers=2 --no-daemon`
- linting fails with an error pointing to a class from the usercentrics SDK:

![image](https://github.com/Usercentrics/android-sample/assets/6364856/7e3cca2f-dc47-450f-a1cb-bd8733a53a5b)

This issue has broken our CI build. Our workaround is to add this issue to the lint baseline.

**Comment by G00fY2** [comment]
We are also facing this issue and ignoring security related issues doesn't seem right. For the context, it's about this lint rule: https://googlesamples.github.io/android-custom-lint-rules/checks/TrustAllX509TrustManager.md.html

> This check looks for X509TrustManager implementations whose checkServerTrusted or checkClientTrusted methods do nothing (thus trusting any certificate chain) which could result in insecure network traffic caused by trusting arbitrary TLS/SSL certificates presented by peers.

Any news on this? @uc-leo

**Comment by BlackHornet** [comment]
+1, very important in case you have a very strict company security which in that case forbid to use UC at all

**Comment by uc-piotukh** [comment]
Hi all!

We have this enabled in order to support Android versions below Lollipop (SDK 22). 
As you can see https://www.appbrain.com/stats/top-android-sdk-versions or https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide those old versions of Android represents a very little amount of market, but we have some customers that need to have those versions enabled.

This is not considered a bug, if you need this to be a hard-requirement (lint rule), you can safely add an exception for this on Usercentrics library.
Should you have any follow-up questions, please feel free to create an apps support ticket through our ticketing portal [here](https://usercentricssupport.zendesk.com/hc/en-us/requests/new).

**Comment by JohannesPtaszyk** [comment]
I have to strongly agree with @G00fY2 on this one. 
Also disabling the lint rule could lead to further security risks, as in case of a real issue with that, which might be introduced in the future, we had no chance of detecting it early.

With the information that @G00fY2 collected already it should be possible to get this fixed fairly quickly. 🤔
